import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { getPortalSnapshot } from "@/lib/portal/backend";

export async function GET(
  _request: Request,
  context: { params: Promise<{ id: string }> },
) {
  const { id } = await context.params;
  const state = await getPortalSnapshot();
  const payslip = state.payslips.find((entry) => entry.id === id);

  if (!payslip) {
    return NextResponse.json({ error: "Payslip not found" }, { status: 404 });
  }

  const payroll = state.payrolls.find((entry) => entry.id === payslip.payrollId);
  const employee = state.employees.find((entry) => entry.id === payslip.employeeId);
  const company = payroll
    ? state.companies.find((entry) => entry.id === payroll.companyId)
    : undefined;

  if (!payroll || !employee) {
    return NextResponse.json({ error: "Payslip data incomplete" }, { status: 400 });
  }

  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  page.drawText("EOR Payslip", { x: 50, y: 780, size: 24, font: bold, color: rgb(0.07, 0.13, 0.26) });
  page.drawText(`${employee.fullName} · ${employee.designation}`, { x: 50, y: 750, size: 12, font: regular });
  page.drawText(`${company?.name ?? "Client company"} · ${payslip.month}`, { x: 50, y: 730, size: 12, font: regular });

  const rows = [
    ["Base Salary", `INR ${payroll.baseSalary.toLocaleString("en-IN")}`],
    ["Tax", `INR ${payroll.tax.toLocaleString("en-IN")}`],
    ["Loss of Pay Deduction", `INR ${payroll.lossOfPayDeduction.toLocaleString("en-IN")}`],
    ["Net Salary", `INR ${payroll.netSalary.toLocaleString("en-IN")}`],
  ];

  rows.forEach(([label, value], index) => {
    const y = 660 - index * 50;
    page.drawRectangle({ x: 50, y: y - 20, width: 495, height: 36, color: rgb(0.97, 0.98, 1) });
    page.drawText(label, { x: 64, y, size: 12, font: bold });
    page.drawText(value, { x: 360, y, size: 12, font: regular });
  });

  page.drawText("Generated by the India-focused EOR portal demo build.", {
    x: 50,
    y: 420,
    size: 10,
    font: regular,
    color: rgb(0.4, 0.46, 0.56),
  });

  const bytes = await pdf.save();

  return new NextResponse(Buffer.from(bytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="${payslip.fileName}"`,
    },
  });
}
